- _sources/Unit1-Using-Objects-and-Methods/topic-1-1-intro-algorithms.rst
- _sources/Unit1-Using-Objects-and-Methods/topic-1-2-variables.rst
- _sources/Unit1-Using-Objects-and-Methods/topic-1-3-expressions.rst
- _sources/Unit3-Class-Creation/topic-3-7-static-vars-methods.rst
New versions of LOs and EKs added, especially to summary.
Moved final variables to 3.7. Moved print vs println to 1.3, especially for AP practice questions.
Also renamed some unique ids for exercises.
> Finished revisions on 1.1 and 1.2

- _sources/Unit1-Using-Objects-and-Methods/topic-1-5-casting.rst
- _sources/Unit1-Using-Objects-and-Methods/topic-1-6-compound-operators.rst
Not too many changes for these.
- Better id names
- Added more to do in the activecodes
- Reworded L.O.'s to match new ones.
- Added (int) casting in L.O.s
- Added something about round-off errors in L.O.s
> Edits 1.5 and 1.6

- move-rst.pl
This script automates moving an rst file from one unit to another, updating both toctrees and doing the `git mv` and `git add`s.
> Script for moving rst files.

- move-rst.pl
Now you can specify either a specific file to move to or just a directory, similar to how unix `mv` works. And if you move a file to a new name in the same directory it replaces the entry in that directory`s `toctree.rst`.
> Some useful tweaks to the move-rst script.

- _sources/HiddenFiles/topic-10-4-toggle-write-code.rst
- _sources/HiddenFiles/topic-7-9-toggle-write-code.rst
- _sources/HiddenFiles/topic-8-4-toggle-write-code.rst
- _sources/HiddenFiles/topic-9-10-toggle-write-code.rst
- _sources/TimedTests/Exercises.rst
- _sources/Unit2-Selection-and-Iteration/loops-practice-mixed-code.rst
- _sources/Unit2-Selection-and-Iteration/selection-more-practice-coding.rst
- _sources/Unit3-Class-Creation/midterm_unit5.rst
- _sources/Unit4-Data-Collections/Array2dMoreCodePractice.rst
- _sources/Unit4-Data-Collections/MoreArrayPractice.rst
- _sources/Unit5-Inheritance/ooCodePractice.rst
- _sources/Unit5-Inheritance/ooParsonsPractice.rst
- _sources/_hidden/Ex-array-orig.rst
Some of the exercises used the term function which is now replaed with method.
> replace function with method 

- _sources/Unit1-Using-Objects-and-Methods/topic-1-12-objects.rst
- _sources/Unit1-Using-Objects-and-Methods/topic-1-13-constructors.rst
- _sources/Unit1-Using-Objects-and-Methods/topic-1-14-calling-instance-methods.rst
- _sources/Unit2-Selection-and-Iteration/topic-2-2-booleans.rst
> 2-2-booleans

- _sources/Unit2-Selection-and-Iteration/topic-2-7-while-loops.rst
- _sources/Unit2-Selection-and-Iteration/topic-2-8-for-loops.rst
Mostly same. Changed challenges a little.
> 2-7 and 2-8 loops

- _sources/Unit3-Class-Creation/topic-3-1-abstraction.rst
- _sources/Unit3-Class-Creation/topic-3-2-impacts.rst
- _sources/Unit3-Class-Creation/topic-3-3-anatomy-of-class.rst
> 3.1 and 3.2 abstraction and impacts

- _sources/Unit3-Class-Creation/topic-3-4-constructors.rst
- pavement.py
> 3-4-constructors

- _sources/Unit3-Class-Creation/topic-3-2-impacts.rst
- _sources/Unit4-Data-Collections/topic-4-1-data-ethics.rst
- _sources/Unit4-Data-Collections/topic-4-2-data-sets.rst
- _sources/Unit4-Data-Collections/topic-4-5-array-algorithms.rst
And some stuff moved from 3-5 and parsons prob fixes to 4-5
> 4-1 and 4-2 data/ethics lessons

- _sources/Unit4-Data-Collections/topic-4-6-input-files.rst
- _sources/Unit4-Data-Collections/topic-4-7-wrapper-classes.rst
4.6  Input files, mostly same, changed nio input back to Scanner io input. 
4.7 Wrappers mostly same, added parse methods, challenge changed
> 4-6 and 4-7 input files and wrappers

- _sources/Unit4-Data-Collections/topic-4-11-2Darrays.rst
- _sources/Unit4-Data-Collections/topic-4-12-2Darray-traversal.rst
Mostly same, but length moved from 4-12 to 4-11, and algorithms moved from 4-12 to 4-13.
> 4-11 2D arrays and 4-12 2D traversals

- _sources/Unit4-Data-Collections/topic-4-14-searching.rst
- _sources/Unit4-Data-Collections/topic-4-15-sorting.rst
Mostly same. Moved 2D linear search here.
> 4-14 search and 4-15 sort

- _sources/Unit4-Data-Collections/topic-4-16-recursion.rst
- _sources/Unit4-Data-Collections/topic-4-17-recursive-search-sort.rst
> 4-16 and 4-17 recursion lessons

- .gitignore
- pretext/FreeResponse/toctree.ptx
- pretext/Unit5-Inheritance/toctree.ptx
- project.ptx
> pretext v2

- pretext/assets/_static/css/custom.css
Paragraph text seemed cramped to me. I think this is better. What do you think?
> Let paragraph text breath a bit.

- pretext/assets/_static/css/custom.css
I'm just tweaking things as I go. Let me know if you'd rather a bundle these changes up into fewer PRs.
> The space between paragraphs seemed a bit too much to me.

- pretext/Unit1-Using-Objects-and-Methods/topic-1-2-variables.ptx
I may have written it originally but wanted to take out the "too crazy" phrasing as potentially ableist.
> Better example of too long variable name.

- pretext/Unit1-Using-Objects-and-Methods/topic-1-2-variables.ptx
I've always disliked this question because doubles are a terrible data type to use for representing money given that they can't represent nickels and dimes exactly.
> Let's not encourage using doubles for money.

- pretext/Unit1-Using-Objects-and-Methods/topic-1-13-constructors.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-14-calling-instance-methods.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-15-strings.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-2-variables.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-5-casting.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-8-comments.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-9-method-signatures.ptx
- pretext/Unit2-Selection-and-Iteration/magpie3.ptx
- pretext/Unit2-Selection-and-Iteration/topic-2-11-nested-loops.ptx
- pretext/Unit2-Selection-and-Iteration/topic-2-4-nested-ifs.ptx
- pretext/Unit4-Data-Collections/pictureLabA1toA3.ptx
- pretext/Unit4-Data-Collections/topic-4-6-input-files.ptx
A cherry picked change from BHSawesome to update all the links to Javadocs. Merge if/when you want.
> Fix Javadoc links.

- pretext/Unit0-Getting-Started/javaIDEs.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-12-objects.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-7-APIs-and-libraries.ptx
- pretext/Unit2-Selection-and-Iteration/FRQmessagebuilder.ptx
- pretext/Unit3-Class-Creation/FRQcupcake.ptx
- pretext/Unit3-Class-Creation/FRQstepTracker.ptx
- pretext/Unit3-Class-Creation/topic-3-6-methods-references.ptx
- pretext/Unit4-Data-Collections/cookieOrderB.ptx
- pretext/Unit4-Data-Collections/topic-4-1-data-ethics.ptx
- pretext/Unit4-Data-Collections/topic-4-14-searching.ptx
- pretext/Unit4-Data-Collections/topic-4-16-recursion.ptx
- pretext/Unit4-Data-Collections/topic-4-6-input-files.ptx
FYI @gigamonkey, these are some small updates from teachers in my Boston workshop last week. You might only want the Typos and Bugs one.  Sorry they're all thrown together in 1 PR.
> Workshop feedback updates

- pretext/Unit0-Getting-Started/javaIDEs.ptx
Changed the link to remove the 
> <em>.html</em>
Fixes issue #172
> Changed the NetBeans link to remedy the 404 error

- pretext/Unit1-Using-Objects-and-Methods/toctree.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-15-strings.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-4-assignment.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-6-compound-operators.ptx
- pretext/Unit1-Using-Objects-and-Methods/topic-1-9-method-signatures.ptx
- pretext/Unit2-Selection-and-Iteration/toctree.ptx
- pretext/Unit2-Selection-and-Iteration/topic-2-12-loop-analysis.ptx
- pretext/Unit2-Selection-and-Iteration/topic-2-6-comparing-booleans.ptx
- pretext/Unit3-Class-Creation/toctree.ptx
- pretext/Unit3-Class-Creation/topic-3-4-constructors.ptx
- pretext/Unit3-Class-Creation/topic-3-9-this.ptx
- pretext/Unit4-Data-Collections/toctree.ptx
- pretext/Unit4-Data-Collections/topic-4-10-arraylist-algorithms.ptx
- pretext/Unit4-Data-Collections/topic-4-13-2Darray-algorithms.ptx
- pretext/Unit4-Data-Collections/topic-4-17-recursive-search-sort.ptx
- pretext/Unit4-Data-Collections/topic-4-5-array-algorithms.ptx
The numbering of progress checks changed from 1, 2, 3, to A, B, C. Added new mentions of AP Classroom labs.
> Update mentions of AP Classroom progress check and lab mentions

- pretext/HiddenFiles/u1a-toggle-write-code.ptx
- pretext/Unit1-Using-Objects-and-Methods/unit1a-practice-mixed-code.ptx
- pretext/Unit1-Using-Objects-and-Methods/unit1a-practice-toggle-code.ptx
Added XML IDs to the exercises in u1a-toggle-write-code.ptx and unit1a-practice-mixed-code.ptx and subsequently added the toggle exercises in unit1a-practice-toggle-code.ptx
> Add unit 1A toggle exercises

- pretext/HiddenFiles/u1b-toggle-write-code.ptx
- pretext/Unit1-Using-Objects-and-Methods/unit1b-practice-mixed-code.ptx
- pretext/Unit1-Using-Objects-and-Methods/unit1b-practice-toggle-code.ptx
Added XML IDs to the exercises in u1b-toggle-write-code.ptx and unit1b-practice-mixed-code.ptx and subsequently added the toggle exercises in unit1b-practice-toggle-code.ptx
> Add unit 1B toggle exercises

- pretext/HiddenFiles/u2a-toggle-write-code.ptx
- pretext/Unit2-Selection-and-Iteration/selection-practice-mixed-code.ptx
- pretext/Unit2-Selection-and-Iteration/unit2a-practice-toggle-code.ptx
Added XML IDs to the exercises in u2a-toggle-write-code.ptx and selection-practice-mixed-code.ptx and subsequently added the toggle exercises in unit2a-practice-toggle-code.ptx
> Add unit 2A toggle exercises

- pretext/HiddenFiles/u2b-toggle-write-code.ptx
- pretext/Unit2-Selection-and-Iteration/loops-practice-mixed-code.ptx
- pretext/Unit2-Selection-and-Iteration/unit2b-practice-toggle-code.ptx
Added XML IDs to the exercises in u2b-toggle-write-code.ptx and loops-practice-mixed-code.ptx and subsequently added the toggle exercises in unit2b-practice-toggle-code.ptx
> Add unit 2B toggle exercises

- pretext/Exercises.ptx
- pretext/HiddenFiles/u2a-toggle-write-code.ptx
- pretext/HiddenFiles/u2b-toggle-write-code.ptx
- pretext/Unit2-Selection-and-Iteration/loops-practice-mixed-code.ptx
- pretext/Unit2-Selection-and-Iteration/selection-practice-mixed-code.ptx
- pretext/Unit2-Selection-and-Iteration/toctree.ptx
- pretext/Unit2-Selection-and-Iteration/unit2a-practice-toggle-code.ptx
- pretext/Unit2-Selection-and-Iteration/unit2b-practice-toggle-code.ptx
Move toggle code lessons into U2 and move mixed-up code to u12.
Also, rename the mixed code ids. Also add in a couple write-codes that were missing.
> U2 toggle code

- pretext/Exercises.ptx
- pretext/HiddenFiles/u1a-toggle-write-code.ptx
- pretext/HiddenFiles/u1b-toggle-write-code.ptx
- pretext/HiddenFiles/u2a-toggle-write-code.ptx
- pretext/HiddenFiles/u2b-toggle-write-code.ptx
- pretext/HiddenFiles/u4a-toggle-write-code.ptx
- pretext/HiddenFiles/u4b-toggle-write-code.ptx
- pretext/HiddenFiles/u4c-toggle-write-code.ptx
- pretext/Unit4-Data-Collections/toctree.ptx
Replacing exercise with activity to fix error in Runestone of not showing instructions.
> Put in unit 4 toggle exs. Replace 'activity' with 'exercise' 
